features=["trip_distance", "driver_distance", "event_hour", "driver_gps_accuracy", "is_peak_hour","actual_idle_time_minutes","pickup_to_trip_ratio","total_commitment_distance"]
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=200
max_depth=30
n_jobs=-1
random_state=42
bootstrap=false
